### PR TITLE
Added drag and drop

### PR DESCRIPTION
**Pull request by alexgorbatchev**
Added drag and drop from another fork. Cleaned up facebook theme a bit.

### CODE REVIEW

**Comment by alexgorbatchev** [comment]
Hold off on this one, for some reason values don't propagate to the hidden_input

**Comment by vdepizzol** [comment]
Hey, Alex, while this is still a work in progress I cleaned facebook theme a bit more. Didn't find a way to send it back to you before I pull the changes, so I putted this here: https://gist.github.com/1015048

Thanks.

**Comment by alexgorbatchev** [comment]
@vdepizzol your css breaks it for me completely for some reason... didn't look into why http://d.pr/N4yf

**Comment by alexgorbatchev** [comment]
k, i figured out the problem in my merge and my master is now fixed

**Comment by vdepizzol** [comment]
Sorry, I only sent to gist the changed elements of the CSS file (from line 1 to 78 of your 94f4bc2b323ae618519dcde6cbe4c781f34f5d86). Now I included the entire file, please take a look again :).

Thanks.

**Comment by alexgorbatchev** [comment]
Done. Integrated your CSS with a few very tiny tweaks. Ready for merging.

**Comment by vdepizzol** [comment]
Hey Alex. Sorry for the delay (gsoc is taking all my time here :))

Just done merging this pull request. In the future however I'd really like to get a drag and drop that has more feedback than those simple borders (maybe creating a semi-transparent duplicated element that moves with the mouse when dragging).

Thank you!

**Comment by alexgorbatchev** [comment]
That would be ideal, but I'm hesitant to require jquery UI for this, it would significantly boost the file size... i think borders effect can definitely be improved on its own however.

**Comment by vdepizzol** [comment]
Hey Alex! I changed a couple of things since merging this code. There was a bug when clicking in the elements (the click and release actions were invoking the drag&drop thing, and it would incorrectly move elements just by clicking on them), and the "active" class was being putted on the wrong time (on clicking, and not on releasing).

Besides this, I started to work on some visual feedback for moving the elements. Make sure to take a look in my last commits ;)

**Comment by alexgorbatchev** [comment]
Awesome, great job!

**Pull request merged**
